name = "ryancruz-com"
compatibility_date = "2024-12-30"
main = "src/worker.ts"

[assets]
directory = "dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

# Custom domain configuration
# Configure custom domain via Cloudflare Dashboard

[vars]
# Environment variables for your worker
