name = "ryancruz-com"
main = ".open-next/worker.js"
compatibility_date = "2024-12-30"
compatibility_flags = [
  "nodejs_compat",
  "global_fetch_strictly_public"
]

[assets]
directory = ".open-next/assets"

# Custom domain will be configured via Cloudflare Dashboard
# No routes section needed for custom domains

[vars]
# Environment variables for your worker