name = "ryancruz-com"
main = "dist/worker.js"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "dist"

# Custom domain configuration
# Configure custom domain via Cloudflare Dashboard

[vars]
# Environment variables for your worker