name = "ryancruz-com"
main = ".open-next/worker.js"
compatibility_date = "2024-12-30"
compatibility_flags = [
  "nodejs_compat",
  "global_fetch_strictly_public"
]

[assets]
directory = ".open-next/assets"

[[routes]]
pattern = "ryancruz.com/*"
custom_domain = true

[vars]
# Environment variables for your worker