name = "ryancruz-com"
compatibility_date = "2024-12-30"

[assets]
directory = "dist"
not_found_handling = "single-page-application"

# Custom domain configuration
# Configure custom domain via Cloudflare Dashboard

[vars]
# Environment variables for your worker